### ISSUE TITLE
Implement User Authentication

### ISSUE THREAD

**Issue by Nitish2004kumar** [Nitish2004kumar/videoCall#1]
Currently anyone who has the link can join the conference. Instead make it more confidential by adding user authentication with username and password. And assigning them particular session.

**Comment by callmeniyu** [comment]
3b0b827: this fixes #1

**Comment by callmeniyu** [comment]
3b0b827: this commit fixes #1

**Comment by callmeniyu** [comment]
3b0b827: this commits fixes the issue #1
